"""Configuration package for the College Accountability Dashboard."""

from .constants import (
    OVERVIEW_SECTION,
    VALUE_GRID_SECTION,
    FEDERAL_LOANS_SECTION,
    PELL_SECTION,
    VALUE_GRID_CHART_CONFIGS,
    VALUE_GRID_CONFIG_MAP,
    VALUE_GRID_OVERVIEW_LABEL,
    FOUR_YEAR_VALUE_GRID_LABEL,
    TWO_YEAR_VALUE_GRID_LABEL,
    PELL_CHARTS,
    PELL_OVERVIEW_LABEL,
    PELL_TOP_DOLLARS_FOUR_LABEL,
    PELL_TOP_DOLLARS_TWO_LABEL,
    PELL_VS_GRAD_FOUR_LABEL,
    PELL_VS_GRAD_TWO_LABEL,
    PELL_TREND_FOUR_LABEL,
    PELL_TREND_TWO_LABEL,
    LOAN_CHARTS,
    LOAN_OVERVIEW_LABEL,
    LOAN_TOP_DOLLARS_FOUR_LABEL,
    LOAN_TOP_DOLLARS_TWO_LABEL,
    LOAN_VS_GRAD_FOUR_LABEL,
    LOAN_VS_GRAD_TWO_LABEL,
    LOAN_TREND_FOUR_LABEL,
    LOAN_TREND_TWO_LABEL,
    ValueGridChartConfig,
)

from .data_sources import DataSources

from .navigation import NavigationConfig, SectionConfig

__all__ = [
    # Sections
    "OVERVIEW_SECTION",
    "VALUE_GRID_SECTION",
    "FEDERAL_LOANS_SECTION",
    "PELL_SECTION",
    # Value Grid
    "VALUE_GRID_CHART_CONFIGS",
    "VALUE_GRID_CONFIG_MAP",
    "VALUE_GRID_OVERVIEW_LABEL",
    "FOUR_YEAR_VALUE_GRID_LABEL",
    "TWO_YEAR_VALUE_GRID_LABEL",
    "ValueGridChartConfig",
    # Pell
    "PELL_CHARTS",
    "PELL_OVERVIEW_LABEL",
    "PELL_TOP_DOLLARS_FOUR_LABEL",
    "PELL_TOP_DOLLARS_TWO_LABEL",
    "PELL_VS_GRAD_FOUR_LABEL",
    "PELL_VS_GRAD_TWO_LABEL",
    "PELL_TREND_FOUR_LABEL",
    "PELL_TREND_TWO_LABEL",
    # Loans
    "LOAN_CHARTS",
    "LOAN_OVERVIEW_LABEL",
    "LOAN_TOP_DOLLARS_FOUR_LABEL",
    "LOAN_TOP_DOLLARS_TWO_LABEL",
    "LOAN_VS_GRAD_FOUR_LABEL",
    "LOAN_VS_GRAD_TWO_LABEL",
    "LOAN_TREND_FOUR_LABEL",
    "LOAN_TREND_TWO_LABEL",
    # Data
    "DataSources",
    # Navigation
    "NavigationConfig",
    "SectionConfig",
]